services:
  chat_app:
    build:
      context: .
      dockerfile: ./chat_app/Dockerfile
    container_name: chat_app
    command: mix phx.server
    volumes:
      - ./chat_app:/app 
    ports:
      - "4000:4000" 
    tty: true  # Maintient le terminal actif
    stdin_open: true  # Maintient l'entrée standard ouverte
